### ISSUE TITLE
Contact Us Message Box Not Expanding

### ISSUE THREAD

**Issue by devanshkat** [devanshkat/purrlicious-boba#9]
ISSUE:
- When typing in the message text input, the box does not resize, making it difficult to read what is to be sent.

SOLUTION:
- Replace text input with auto-growing textarea (see here for more info on how to implement: [Auto-Growing Textarea with Tailwind CSS](https://cruip.com/auto-growing-textarea-with-tailwind-css/)

**Comment by AdithyaBollu** [comment]
Added a Text Area that can be manually grown or shrunk by the user.
